// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7z1JaLsqy-lXtziI6G-o-BdMS10syPws',
    appId: '1:191999171573:web:6cdf8e676e086de1515ebc',
    messagingSenderId: '191999171573',
    projectId: 'ly-instagram',
    authDomain: 'ly-instagram.firebaseapp.com',
    storageBucket: 'ly-instagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbSB5LBG_qgRuhdrgPMcMP-4LhN-ktdM',
    appId: '1:191999171573:android:f736e808ed7db613515ebc',
    messagingSenderId: '191999171573',
    projectId: 'ly-instagram',
    storageBucket: 'ly-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PkAMfSBUJKqBrDF23moorU3jRZldl9s',
    appId: '1:191999171573:ios:b94d7e65c2d78798515ebc',
    messagingSenderId: '191999171573',
    projectId: 'ly-instagram',
    storageBucket: 'ly-instagram.appspot.com',
    iosClientId: '191999171573-r8r9l9tphnbh99ldidgvbv64ua5mh2th.apps.googleusercontent.com',
    iosBundleId: 'com.example.ly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PkAMfSBUJKqBrDF23moorU3jRZldl9s',
    appId: '1:191999171573:ios:b94d7e65c2d78798515ebc',
    messagingSenderId: '191999171573',
    projectId: 'ly-instagram',
    storageBucket: 'ly-instagram.appspot.com',
    iosClientId: '191999171573-r8r9l9tphnbh99ldidgvbv64ua5mh2th.apps.googleusercontent.com',
    iosBundleId: 'com.example.ly',
  );
}
